name: Deploy Frontend
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t shafiqullahturkmen/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true shafiqullahturkmen/react-test npm test
      - run: docker build -t shafiqullahturkmen/multi-client ./client
      - run: docker build -t shafiqullahturkmen/multi-nginx ./nginx
      - run: docker build -t shafiqullahturkmen/multi-server ./server
      - run: docker build -t shafiqullahturkmen/multi-worker ./worker
      - run: docker push shafiqullahturkmen/multi-client 
      - run: docker push shafiqullahturkmen/multi-nginx 
      - run: docker push shafiqullahturkmen/multi-server 
      - run: docker push shafiqullahturkmen/multi-worker  
    
      # - name: Generate deployment package
      #   run:  zip -r deploy.zip . -x "*.git*"
      
      # - name: Deploy to EB
      #   uses: einaregilsson/beanstalk-deploy@v18
      #   with:
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      #     aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
      #     application_name: docker
      #     environment_name: Docker-env
      #     existing_bucket_name: elasticbeanstalk-us-east-1-040884524510
      #     region: us-east-1
      #     version_label: ${{ github.sha }}
      #     deployment_package: deploy.zip